### ISSUE TITLE
EPIC: Support libp2p/test-plan transition from ipdx ownership to libp2p

### ISSUE THREAD

**Issue by laurentsenta** [libp2p/test-plans#51]
- [ ] make sure the roadmap has an owner
- [ ] share the benchmarking scripts + procedures
- [ ] share drafts to automate updates if needed
